version: '3.8'

services:
  app:
    image: food_app_server
    container_name: food_app
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8080:8080
    environment:
      PORT: 8080
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    depends_on:
      - db

  db:
    image: postgres:13-bullseye
    environment: 
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - 5432:5432

    