version: '3.8'

services:
  app:
    image: food_app_server
    container_name: food_app
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8080:8080
    environment:
      PORT: 8080
    