import { CreateProductDto } from "../../../modules/products/dto/create-product.dto";

export const products: CreateProductDto[] = [
    {
        product_name: "Hamburguesa Sencilla",
        price: 8.99,
        categories: ["Hamburguesas"],
        description: "Hamburguesa doble especial, con carne Angus y salsa especial de la casa.",
        discount: false,
        discount_rate: 0,
    },
    {
        product_name: "Hamburguesa Doble Queso",
        price: 9.99,
        categories: ["Hamburguesas"],
        description: "Hamburguesa doble especial, con carne Angus y salsa especial de la casa.",
        discount: false,
        discount_rate: 0,
    },
    {
        product_name: "Baconnator",
        price: 12.99,
        categories: ["Hamburguesas"],
        description: "Hamburguesa doble especial, con carne Angus y salsa especial de la casa.",
        discount: false,
        discount_rate: 0,
    },
    {
        product_name: "Vegan",
        price: 13.66,
        categories: ["Hamburguesas"],
        description: "Hamburguesa doble especial, con carne Angus y salsa especial de la casa.",
        discount: false,
        discount_rate: 0,
    },
    {
        product_name: "Vegan",
        price: 13.66,
        categories: ["Hamburguesas"],
        description: "Hamburguesa doble especial, con carne Angus y salsa especial de la casa.",
        discount: false,
        discount_rate: 0,
    },
    {
        product_name: "Vegan",
        price: 13.66,
        categories: ["Hamburguesas"],
        description: "Hamburguesa doble especial, con carne Angus y salsa especial de la casa.",
        discount: false,
        discount_rate: 0,
    },
    {
        product_name: "Vegan",
        price: 13.66,
        categories: ["Hamburguesas"],
        description: "Hamburguesa doble especial, con carne Angus y salsa especial de la casa.",
        discount: false,
        discount_rate: 0,
    },
    {
        product_name: "Vegan",
        price: 13.66,
        categories: ["Hamburguesas"],
        description: "Hamburguesa doble especial, con carne Angus y salsa especial de la casa.",
        discount: false,
        discount_rate: 0,
    },
    {
        product_name: "Vegan",
        price: 13.66,
        categories: ["Pizza"],
        description: "Hamburguesa doble especial, con carne Angus y salsa especial de la casa.",
        discount: false,
        discount_rate: 0,
    },
    {
        product_name: "Vegan",
        price: 13.66,
        categories: ["Pizza"],
        description: "Hamburguesa doble especial, con carne Angus y salsa especial de la casa.",
        discount: false,
        discount_rate: 0,
    },
    {
        product_name: "Vegan",
        price: 13.66,
        categories: ["Pizza"],
        description: "Hamburguesa doble especial, con carne Angus y salsa especial de la casa.",
        discount: false,
        discount_rate: 0,
    },
    {
        product_name: "Vegan",
        price: 13.66,
        categories: ["Pizza"],
        description: "Hamburguesa doble especial, con carne Angus y salsa especial de la casa.",
        discount: false,
        discount_rate: 0,
    },
    {
        product_name: "Vegan",
        price: 13.66,
        categories: ["Pizza"],
        description: "Hamburguesa doble especial, con carne Angus y salsa especial de la casa.",
        discount: false,
        discount_rate: 0,
    },
    {
        product_name: "Vegan",
        price: 13.66,
        categories: ["Pizza"],
        description: "Hamburguesa doble especial, con carne Angus y salsa especial de la casa.",
        discount: false,
        discount_rate: 0,
    },
    {
        product_name: "Vegan",
        price: 13.66,
        categories: ["Pollo"],
        description: "Hamburguesa doble especial, con carne Angus y salsa especial de la casa.",
        discount: false,
        discount_rate: 0,
    },
    {
        product_name: "Vegan",
        price: 13.66,
        categories: ["Pollo"],
        description: "Hamburguesa doble especial, con carne Angus y salsa especial de la casa.",
        discount: false,
        discount_rate: 0,
    },
    {
        product_name: "Vegan",
        price: 13.66,
        categories: ["Pollo"],
        description: "Hamburguesa doble especial, con carne Angus y salsa especial de la casa.",
        discount: false,
        discount_rate: 0,
    },
    {
        product_name: "Vegan",
        price: 13.66,
        categories: ["Pollo"],
        description: "Hamburguesa doble especial, con carne Angus y salsa especial de la casa.",
        discount: false,
        discount_rate: 0,
    },
    {
        product_name: "Vegan",
        price: 13.66,
        categories: ["Pollo"],
        description: "Hamburguesa doble especial, con carne Angus y salsa especial de la casa.",
        discount: false,
        discount_rate: 0,
    },
    {
        product_name: "Vegan",
        price: 13.66,
        categories: ["Pollo"],
        description: "Hamburguesa doble especial, con carne Angus y salsa especial de la casa.",
        discount: false,
        discount_rate: 0,
    },
    {
        product_name: "Vegan",
        price: 13.66,
        categories: ["Complementos"],
        description: "Hamburguesa doble especial, con carne Angus y salsa especial de la casa.",
        discount: false,
        discount_rate: 0,
    },
    {
        product_name: "Vegan",
        price: 13.66,
        categories: ["Complementos"],
        description: "Hamburguesa doble especial, con carne Angus y salsa especial de la casa.",
        discount: false,
        discount_rate: 0,
    },
    {
        product_name: "Vegan",
        price: 13.66,
        categories: ["Complementos"],
        description: "Hamburguesa doble especial, con carne Angus y salsa especial de la casa.",
        discount: false,
        discount_rate: 0,
    },
    {
        product_name: "Vegan",
        price: 13.66,
        categories: ["Complementos"],
        description: "Hamburguesa doble especial, con carne Angus y salsa especial de la casa.",
        discount: false,
        discount_rate: 0,
    },
    {
        product_name: "Vegan",
        price: 13.66,
        categories: ["Complementos"],
        description: "Hamburguesa doble especial, con carne Angus y salsa especial de la casa.",
        discount: false,
        discount_rate: 0,
    },
    {
        product_name: "Vegan",
        price: 13.66,
        categories: ["Complementos"],
        description: "Hamburguesa doble especial, con carne Angus y salsa especial de la casa.",
        discount: false,
        discount_rate: 0,
    },
];